### ISSUE TITLE
Student Contact Info

### ISSUE THREAD

**Issue by acifuen1** [D-Nguyen88/Fall-2018---4350---Software-Engineering#29]
If you encounter something or know of anything related to this epic. Add it as an issue, the more the better.

**Comment by D-Nguyen88** [comment]
Get some Student linkedin ID number. 10 max

Your LinkedIn User ID
Your LinkedIn ID is a number that LinkedIn generates for you when you first sign up for a LinkedIn account. Internally, it uses the number to keep track of your account; there are many users named "Joe Smith," but the system only allows there to be one user number 14,037,643, for example. The system assigns ID numbers in the order in which users sign up for a LinkedIn account, so people who have been on LinkedIn for a longer period of time will have a lower user ID number.

Finding Your ID
To find your ID, log in to your LinkedIn account and hold your mouse over a link to your Profile, such as the one in the top menu bar. Look in your browser's status bar, which is usually at the bottom of the window. You will see LinkedIn's internal uniform resource locator for your profile. The middle of the URL will say "view?id=XXXXXX&trk=," where XXXXXX represents your numeric user ID.

Using the ID
During regular site use, you will probably not ever need to know your exact LinkedIn ID. However, if you are developing a site or an application that taps into LinkedIn through its application programming interface, you might find it useful. LinkedIn's API allows you to look up users and access their data by their numeric ID, which may be easier for your program to track than a full name.
